# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.network :hostonly, "33.33.33.10"

  # Forward a port from the guest to the host, which allows for outside
  # computers to access the VM, whereas host only networking does not.
  # config.vm.forward_port "http", 80, 8080

  # Share an additional folder to the guest VM. The first argument is
  # an identifier, the second is the path on the guest to mount the
  # folder, and the third is the path on the host to the actual folder.
  # config.vm.share_folder "v-data", "/vagrant_data", "../data"

  config.vm.provision :shell, :path => "provision.sh"

  config.vm.share_folder("endpoint", "/data/gopath/src/github.com/racker/go-agent-endpoint", "../..", :nfs => true)
  # ^^ If this line is commented out, `reload` succeeds; otherwise it complains about "Mounting NFS shared folders failed..." and is not mounted. Other two are monted well.

end
