# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|

  config.vm.box = "raring64"
  config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/raring/current/raring-server-cloudimg-amd64-vagrant-disk1.box"

  config.vm.network :hostonly, "33.33.33.10"

  config.vm.forward_port 8088, 8088

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "manifests"
    puppet.manifest_file  = "raring.pp"
  end

  #config.vm.provision :shell, :path => "provision.sh"

  config.vm.share_folder("endpoint", "/data/gopath/src/github.com/virgo-agent-toolkit/go-agent-endpoint", "../..", :nfs => true)

end
